baseURL = "https://whde.github.io/"
languageCode = "en"
title = "sss"
theme = "m10c"
weight = 1

[params]
  # Author
  author = "sss"
  # Description
  description = "Same Mistakes"


[[params.social]]
  name = "github"
  url = "https://github.com/Whde"


[params.style]
#    darkestColor = "#F7F7F7"
#    darkColor = "#212121"
#    primaryColor = "#00CD66"
#    lightColor = "#FFA500"
   lightestColor = "#00CD66"

theme = "m10c"
